In [3]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [7]:
li1 = [
    [1, 2, 3],
    [4, 5, 6]
]
print(li1)
print(type(li1))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


In [9]:
arr3 = np.array([
    [[1, 2],
     [3, 4]],
     [[5, 6],
      [7, 8]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
ones = np.ones((2, 3))   # 2행, 3열
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
range_arr = np.arange(1, 10,2)
print(range_arr)

[1 3 5 7 9]


In [16]:
# 데이터 타입
정수 = np.array([1, 2, 3, 4, 5])
정수.dtype

dtype('int64')

In [18]:
실수 = np.array([1.5, 2.5, 3.5])
실수.dtype

dtype('float64')

In [ ]:
# 배열 속성
arr1 = np.array([1, 2, 3, 4])
arr1.shape   # 튜플 형태로 나옴(1차원 배열이고 4개의 요소를 가지고 있다는 의미)


(4,)

In [20]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr2.shape

(2, 3)

In [21]:
arr3 = np.array([
    [[1, 2],
     [3, 4]],
     [[5, 6],
      [7, 8]]
])
arr3.shape

(2, 2, 2)

In [ ]:
# ndim( 몇 차원인지 나타냄)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [25]:
# size( 배열의 총 요소 수를 알려줌)
arr1 = np.array([1, 2, 3, 4])
print(arr1.size)

4


In [26]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2.size)

6


In [27]:
arr3 = np.array([
    [[1, 2],
     [3, 4]],
     [[5, 6],
      [7, 8]]
])
arr3.size

8