In [1]:
# reshape
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

(6,)


In [7]:
reshaped = arr.reshape((2, 3))
print(reshaped.shape)
print(reshaped)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [5]:
print(arr)

[1 2 3 4 5 6]


In [9]:
# astype
## 데이터타입을 변경한다
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.astype(float))

[1. 2. 3. 4. 5. 6.]


In [17]:
# ravel(다차원 배열을 1차원 배열로 변경)
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print(reshaped)

raveled = reshaped.ravel()
print(raveled)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# flatten ( 다차원 배열을 일차원 배열로 변경)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)
flattened = arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [23]:
# transpose ( 배열의 축을 바꿈)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
transposed = arr.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
# 수학연산
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


In [29]:
# 배열 간 비교 연산

arr1 = np.array([5, 3, 3])
arr2 = np.array([1, 2, 6])
print(arr1 > arr2)
print(arr1 == arr2)

[ True  True False]
[False False False]


In [32]:
# 배열 간의 논리 연산
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, True])
print(arr1 & arr2)
print(arr1 | arr2)

[False False  True]
[ True  True  True]


In [35]:
# 배열 간 집계 연산
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())
print(arr.mean())

15
3.0


In [36]:
arr = np.array([1, 2, 3, 4, 5])
scalar = 2
print(arr * scalar)

[ 2  4  6  8 10]
